cflags="-Ibgfx/bgfx/include -Ibgfx/bx/include -Ibgfx/bimg/include -DBX_CONFIG_DEBUG=1"
ldflags="-Lbgfx/bgfx/.build/linux64_clang/bin/ -lbgfxRelease -lbimg_decodeRelease -lbimgRelease -lbxRelease -lglfw -ldl -lGL -lX11"
multithreaded=true